### ISSUE TITLE
Few suggestions. 

### ISSUE THREAD

**Issue by Moorsy-AU** [DonMcD/ultimate-plex-stack#10]
Plex Meta Manager - Is now Kometa, which I'm sure you already know. 
Maintainerr - Looks like Overseerr, does the opposite. Nice GUI. 
Ive been playing around with Ombi also, like overseer but has an android/apple app and you can request music straight to lidarr. If only overseerr did this.... 

You could add in Recyclarr - does trash guides suggestions automatically.

**Comment by Feramance** [comment]
and qBitrr for overall better automated torrent handling with the ARR suite

**Comment by DonMcD** [comment]
Wow thank you both! I am going to wait a bit before I integrate qBittr into this just because it does look like it is in early development. Recyclarr and Maintainerr are both very cool though, will be adding these!

**Comment by Feramance** [comment]
Hi @DonMcD, qBitrr is far from early development, it's very late development and not much else could be added/changed. I'm also the maintainer for it
