### ISSUE TITLE
Gluetun is missing

### ISSUE THREAD

**Issue by niicholai** [DonMcD/ultimate-plex-stack#11]
Isn't Gluetun supposed to be part of the compose? Checked it several times and it is missing. I am wondering if there's a reason for that, as when I try to add it in manually I am getting network errors on the compose.

EDIT: Nevermind, checked the yaml history and saw it was removed and why, closing, thank you!

**Comment by dlecan** [comment]
Link to explanation: https://github.com/DonMcD/ultimate-plex-stack/commit/d47c05cd30d3850e44fde719e490e518cf3d01fc
