### ISSUE TITLE
Synology

### ISSUE THREAD

**Issue by ZillowwCode** [DonMcD/ultimate-plex-stack#8]
Hello!

Little question here, would it be possible for me to clone this repo via ssh in my synology and then run the docker command to pull all the containers? Or is there any other way to do it in a more synology-oriented way?

**Comment by Feramance** [comment]
You should be able to install docker-compose and then run `docker compose up -d` in the terminal where the compose file is located. Fix environment variables and volumes to suit your setup

**Comment by ZillowwCode** [comment]
@Feramance I'll try that. Thank you!
