### ISSUE TITLE
Exposing this stack to the internet

### ISSUE THREAD

**Issue by ZillowwCode** [DonMcD/ultimate-plex-stack#9]
Hey folks!

Once all of this setup, how would you expose these services to the internet? For example, I would like to make Prowlarr publicly accessible from a subdomain of my domain name. How would you do this? Thank you in advance.

**Comment by Feramance** [comment]
Nginx proxy manager, Traefik or Swag are good options

**Comment by ZillowwCode** [comment]
@Feramance Do you have any source to make these setups?

**Comment by Feramance** [comment]
I personally found swag to need very little config and is what I'm using, just follow the guide on the linuxserver wiki or ask their discord for help. Traefik and nginx proxy manager I haven't used but I know can work and they have a web UI. Wikis and discords will help here

**Comment by ZillowwCode** [comment]
Thank you for your informations. I'll take a look at all of the solutions to find the more suitable for me :)
